#!/usr/bin/env bash
# Copyright 2023 Bryan C. Roessler
#
# btrbk wrapper to return latest target subvolume
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


(( EUID > 0 )) && echo "Please run as root." && exit 1

target="$1" # router.lan:/mnt/backup/media/music

shift

btrbk --dry-run "$@" &&
btrbk list latest --format=col:h:TARGET_HOST,TARGET_SUBVOLUME "$target"